#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtelResepsiyon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OTELdb")]
	public partial class OtelModelDataContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertYonetici(Yonetici instance);
    partial void UpdateYonetici(Yonetici instance);
    partial void DeleteYonetici(Yonetici instance);
    partial void InsertVardiya(Vardiya instance);
    partial void UpdateVardiya(Vardiya instance);
    partial void DeleteVardiya(Vardiya instance);
    partial void InsertRezervasyon(Rezervasyon instance);
    partial void UpdateRezervasyon(Rezervasyon instance);
    partial void DeleteRezervasyon(Rezervasyon instance);
    partial void InsertPersonel(Personel instance);
    partial void UpdatePersonel(Personel instance);
    partial void DeletePersonel(Personel instance);
    partial void InsertPaket(Paket instance);
    partial void UpdatePaket(Paket instance);
    partial void DeletePaket(Paket instance);
    partial void InsertOtelTanitim(OtelTanitim instance);
    partial void UpdateOtelTanitim(OtelTanitim instance);
    partial void DeleteOtelTanitim(OtelTanitim instance);
    partial void InsertOda(Oda instance);
    partial void UpdateOda(Oda instance);
    partial void DeleteOda(Oda instance);
    partial void InsertMusteri(Musteri instance);
    partial void UpdateMusteri(Musteri instance);
    partial void DeleteMusteri(Musteri instance);
    partial void Insert__MigrationHistory(__MigrationHistory instance);
    partial void Update__MigrationHistory(__MigrationHistory instance);
    partial void Delete__MigrationHistory(__MigrationHistory instance);
    #endregion
		
		public OtelModelDataContextDataContext() : 
				base(global::OtelResepsiyon.Properties.Settings.Default.OTELdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OtelModelDataContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OtelModelDataContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OtelModelDataContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OtelModelDataContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Yonetici> Yoneticis
		{
			get
			{
				return this.GetTable<Yonetici>();
			}
		}
		
		public System.Data.Linq.Table<Vardiya> Vardiyas
		{
			get
			{
				return this.GetTable<Vardiya>();
			}
		}
		
		public System.Data.Linq.Table<Rezervasyon> Rezervasyons
		{
			get
			{
				return this.GetTable<Rezervasyon>();
			}
		}
		
		public System.Data.Linq.Table<Personel> Personels
		{
			get
			{
				return this.GetTable<Personel>();
			}
		}
		
		public System.Data.Linq.Table<Paket> Pakets
		{
			get
			{
				return this.GetTable<Paket>();
			}
		}
		
		public System.Data.Linq.Table<OtelTanitim> OtelTanitims
		{
			get
			{
				return this.GetTable<OtelTanitim>();
			}
		}
		
		public System.Data.Linq.Table<Oda> Odas
		{
			get
			{
				return this.GetTable<Oda>();
			}
		}
		
		public System.Data.Linq.Table<Musteri> Musteris
		{
			get
			{
				return this.GetTable<Musteri>();
			}
		}
		
		public System.Data.Linq.Table<@__MigrationHistory> @__MigrationHistories
		{
			get
			{
				return this.GetTable<@__MigrationHistory>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yoneticis")]
	public partial class Yonetici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _YoneticiId;
		
		private string _Ad;
		
		private string _Soyad;
		
		private int _Maas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYoneticiIdChanging(int value);
    partial void OnYoneticiIdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnMaasChanging(int value);
    partial void OnMaasChanged();
    #endregion
		
		public Yonetici()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YoneticiId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int YoneticiId
		{
			get
			{
				return this._YoneticiId;
			}
			set
			{
				if ((this._YoneticiId != value))
				{
					this.OnYoneticiIdChanging(value);
					this.SendPropertyChanging();
					this._YoneticiId = value;
					this.SendPropertyChanged("YoneticiId");
					this.OnYoneticiIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maas", DbType="Int NOT NULL")]
		public int Maas
		{
			get
			{
				return this._Maas;
			}
			set
			{
				if ((this._Maas != value))
				{
					this.OnMaasChanging(value);
					this.SendPropertyChanging();
					this._Maas = value;
					this.SendPropertyChanged("Maas");
					this.OnMaasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vardiyas")]
	public partial class Vardiya : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _vardiyaId;
		
		private System.DateTime _baslangic_saati;
		
		private System.DateTime _bitis_saati;
		
		private int _mesai_saati;
		
		private EntitySet<Personel> _Personels;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvardiyaIdChanging(int value);
    partial void OnvardiyaIdChanged();
    partial void Onbaslangic_saatiChanging(System.DateTime value);
    partial void Onbaslangic_saatiChanged();
    partial void Onbitis_saatiChanging(System.DateTime value);
    partial void Onbitis_saatiChanged();
    partial void Onmesai_saatiChanging(int value);
    partial void Onmesai_saatiChanged();
    #endregion
		
		public Vardiya()
		{
			this._Personels = new EntitySet<Personel>(new Action<Personel>(this.attach_Personels), new Action<Personel>(this.detach_Personels));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vardiyaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int vardiyaId
		{
			get
			{
				return this._vardiyaId;
			}
			set
			{
				if ((this._vardiyaId != value))
				{
					this.OnvardiyaIdChanging(value);
					this.SendPropertyChanging();
					this._vardiyaId = value;
					this.SendPropertyChanged("vardiyaId");
					this.OnvardiyaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baslangic_saati", DbType="DateTime NOT NULL")]
		public System.DateTime baslangic_saati
		{
			get
			{
				return this._baslangic_saati;
			}
			set
			{
				if ((this._baslangic_saati != value))
				{
					this.Onbaslangic_saatiChanging(value);
					this.SendPropertyChanging();
					this._baslangic_saati = value;
					this.SendPropertyChanged("baslangic_saati");
					this.Onbaslangic_saatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bitis_saati", DbType="DateTime NOT NULL")]
		public System.DateTime bitis_saati
		{
			get
			{
				return this._bitis_saati;
			}
			set
			{
				if ((this._bitis_saati != value))
				{
					this.Onbitis_saatiChanging(value);
					this.SendPropertyChanging();
					this._bitis_saati = value;
					this.SendPropertyChanged("bitis_saati");
					this.Onbitis_saatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mesai_saati", DbType="Int NOT NULL")]
		public int mesai_saati
		{
			get
			{
				return this._mesai_saati;
			}
			set
			{
				if ((this._mesai_saati != value))
				{
					this.Onmesai_saatiChanging(value);
					this.SendPropertyChanging();
					this._mesai_saati = value;
					this.SendPropertyChanged("mesai_saati");
					this.Onmesai_saatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vardiya_Personel", Storage="_Personels", ThisKey="vardiyaId", OtherKey="Vardiya_vardiyaId")]
		public EntitySet<Personel> Personels
		{
			get
			{
				return this._Personels;
			}
			set
			{
				this._Personels.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Personels(Personel entity)
		{
			this.SendPropertyChanging();
			entity.Vardiya = this;
		}
		
		private void detach_Personels(Personel entity)
		{
			this.SendPropertyChanging();
			entity.Vardiya = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Rezervasyons")]
	public partial class Rezervasyon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RezervasyonId;
		
		private System.DateTime _girisTarih;
		
		private System.DateTime _cikisTarih;
		
		private System.DateTime _RezervasyonTarih;
		
		private System.Nullable<int> _Musteri_MusteriId;
		
		private System.Nullable<int> _Oda_odaId;
		
		private EntityRef<Oda> _Oda;
		
		private EntityRef<Musteri> _Musteri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRezervasyonIdChanging(int value);
    partial void OnRezervasyonIdChanged();
    partial void OngirisTarihChanging(System.DateTime value);
    partial void OngirisTarihChanged();
    partial void OncikisTarihChanging(System.DateTime value);
    partial void OncikisTarihChanged();
    partial void OnRezervasyonTarihChanging(System.DateTime value);
    partial void OnRezervasyonTarihChanged();
    partial void OnMusteri_MusteriIdChanging(System.Nullable<int> value);
    partial void OnMusteri_MusteriIdChanged();
    partial void OnOda_odaIdChanging(System.Nullable<int> value);
    partial void OnOda_odaIdChanged();
    #endregion
		
		public Rezervasyon()
		{
			this._Oda = default(EntityRef<Oda>);
			this._Musteri = default(EntityRef<Musteri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RezervasyonId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RezervasyonId
		{
			get
			{
				return this._RezervasyonId;
			}
			set
			{
				if ((this._RezervasyonId != value))
				{
					this.OnRezervasyonIdChanging(value);
					this.SendPropertyChanging();
					this._RezervasyonId = value;
					this.SendPropertyChanged("RezervasyonId");
					this.OnRezervasyonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_girisTarih", DbType="DateTime NOT NULL")]
		public System.DateTime girisTarih
		{
			get
			{
				return this._girisTarih;
			}
			set
			{
				if ((this._girisTarih != value))
				{
					this.OngirisTarihChanging(value);
					this.SendPropertyChanging();
					this._girisTarih = value;
					this.SendPropertyChanged("girisTarih");
					this.OngirisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cikisTarih", DbType="DateTime NOT NULL")]
		public System.DateTime cikisTarih
		{
			get
			{
				return this._cikisTarih;
			}
			set
			{
				if ((this._cikisTarih != value))
				{
					this.OncikisTarihChanging(value);
					this.SendPropertyChanging();
					this._cikisTarih = value;
					this.SendPropertyChanged("cikisTarih");
					this.OncikisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RezervasyonTarih", DbType="DateTime NOT NULL")]
		public System.DateTime RezervasyonTarih
		{
			get
			{
				return this._RezervasyonTarih;
			}
			set
			{
				if ((this._RezervasyonTarih != value))
				{
					this.OnRezervasyonTarihChanging(value);
					this.SendPropertyChanging();
					this._RezervasyonTarih = value;
					this.SendPropertyChanged("RezervasyonTarih");
					this.OnRezervasyonTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Musteri_MusteriId", DbType="Int")]
		public System.Nullable<int> Musteri_MusteriId
		{
			get
			{
				return this._Musteri_MusteriId;
			}
			set
			{
				if ((this._Musteri_MusteriId != value))
				{
					if (this._Musteri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMusteri_MusteriIdChanging(value);
					this.SendPropertyChanging();
					this._Musteri_MusteriId = value;
					this.SendPropertyChanged("Musteri_MusteriId");
					this.OnMusteri_MusteriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oda_odaId", DbType="Int")]
		public System.Nullable<int> Oda_odaId
		{
			get
			{
				return this._Oda_odaId;
			}
			set
			{
				if ((this._Oda_odaId != value))
				{
					if (this._Oda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOda_odaIdChanging(value);
					this.SendPropertyChanging();
					this._Oda_odaId = value;
					this.SendPropertyChanged("Oda_odaId");
					this.OnOda_odaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Oda_Rezervasyon", Storage="_Oda", ThisKey="Oda_odaId", OtherKey="odaId", IsForeignKey=true)]
		public Oda Oda
		{
			get
			{
				return this._Oda.Entity;
			}
			set
			{
				Oda previousValue = this._Oda.Entity;
				if (((previousValue != value) 
							|| (this._Oda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Oda.Entity = null;
						previousValue.Rezervasyons.Remove(this);
					}
					this._Oda.Entity = value;
					if ((value != null))
					{
						value.Rezervasyons.Add(this);
						this._Oda_odaId = value.odaId;
					}
					else
					{
						this._Oda_odaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Oda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteri_Rezervasyon", Storage="_Musteri", ThisKey="Musteri_MusteriId", OtherKey="MusteriId", IsForeignKey=true)]
		public Musteri Musteri
		{
			get
			{
				return this._Musteri.Entity;
			}
			set
			{
				Musteri previousValue = this._Musteri.Entity;
				if (((previousValue != value) 
							|| (this._Musteri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Musteri.Entity = null;
						previousValue.Rezervasyons.Remove(this);
					}
					this._Musteri.Entity = value;
					if ((value != null))
					{
						value.Rezervasyons.Add(this);
						this._Musteri_MusteriId = value.MusteriId;
					}
					else
					{
						this._Musteri_MusteriId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Musteri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personels")]
	public partial class Personel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _personelId;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Gorev;
		
		private double _saatlikUcret;
		
		private int _telefon;
		
		private string _Adres;
		
		private System.Nullable<int> _Vardiya_vardiyaId;
		
		private string _sifre;
		
		private EntityRef<Vardiya> _Vardiya;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpersonelIdChanging(int value);
    partial void OnpersonelIdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnGorevChanging(string value);
    partial void OnGorevChanged();
    partial void OnsaatlikUcretChanging(double value);
    partial void OnsaatlikUcretChanged();
    partial void OntelefonChanging(int value);
    partial void OntelefonChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnVardiya_vardiyaIdChanging(System.Nullable<int> value);
    partial void OnVardiya_vardiyaIdChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    #endregion
		
		public Personel()
		{
			this._Vardiya = default(EntityRef<Vardiya>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personelId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int personelId
		{
			get
			{
				return this._personelId;
			}
			set
			{
				if ((this._personelId != value))
				{
					this.OnpersonelIdChanging(value);
					this.SendPropertyChanging();
					this._personelId = value;
					this.SendPropertyChanged("personelId");
					this.OnpersonelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gorev", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gorev
		{
			get
			{
				return this._Gorev;
			}
			set
			{
				if ((this._Gorev != value))
				{
					this.OnGorevChanging(value);
					this.SendPropertyChanging();
					this._Gorev = value;
					this.SendPropertyChanged("Gorev");
					this.OnGorevChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saatlikUcret", DbType="Float NOT NULL")]
		public double saatlikUcret
		{
			get
			{
				return this._saatlikUcret;
			}
			set
			{
				if ((this._saatlikUcret != value))
				{
					this.OnsaatlikUcretChanging(value);
					this.SendPropertyChanging();
					this._saatlikUcret = value;
					this.SendPropertyChanged("saatlikUcret");
					this.OnsaatlikUcretChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="Int NOT NULL")]
		public int telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vardiya_vardiyaId", DbType="Int")]
		public System.Nullable<int> Vardiya_vardiyaId
		{
			get
			{
				return this._Vardiya_vardiyaId;
			}
			set
			{
				if ((this._Vardiya_vardiyaId != value))
				{
					if (this._Vardiya.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVardiya_vardiyaIdChanging(value);
					this.SendPropertyChanging();
					this._Vardiya_vardiyaId = value;
					this.SendPropertyChanged("Vardiya_vardiyaId");
					this.OnVardiya_vardiyaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Vardiya_Personel", Storage="_Vardiya", ThisKey="Vardiya_vardiyaId", OtherKey="vardiyaId", IsForeignKey=true)]
		public Vardiya Vardiya
		{
			get
			{
				return this._Vardiya.Entity;
			}
			set
			{
				Vardiya previousValue = this._Vardiya.Entity;
				if (((previousValue != value) 
							|| (this._Vardiya.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vardiya.Entity = null;
						previousValue.Personels.Remove(this);
					}
					this._Vardiya.Entity = value;
					if ((value != null))
					{
						value.Personels.Add(this);
						this._Vardiya_vardiyaId = value.vardiyaId;
					}
					else
					{
						this._Vardiya_vardiyaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Vardiya");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pakets")]
	public partial class Paket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _paketId;
		
		private string _paketOzellik;
		
		private EntitySet<Oda> _Odas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpaketIdChanging(int value);
    partial void OnpaketIdChanged();
    partial void OnpaketOzellikChanging(string value);
    partial void OnpaketOzellikChanged();
    #endregion
		
		public Paket()
		{
			this._Odas = new EntitySet<Oda>(new Action<Oda>(this.attach_Odas), new Action<Oda>(this.detach_Odas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paketId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int paketId
		{
			get
			{
				return this._paketId;
			}
			set
			{
				if ((this._paketId != value))
				{
					this.OnpaketIdChanging(value);
					this.SendPropertyChanging();
					this._paketId = value;
					this.SendPropertyChanged("paketId");
					this.OnpaketIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paketOzellik", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string paketOzellik
		{
			get
			{
				return this._paketOzellik;
			}
			set
			{
				if ((this._paketOzellik != value))
				{
					this.OnpaketOzellikChanging(value);
					this.SendPropertyChanging();
					this._paketOzellik = value;
					this.SendPropertyChanged("paketOzellik");
					this.OnpaketOzellikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paket_Oda", Storage="_Odas", ThisKey="paketId", OtherKey="Paket_paketId")]
		public EntitySet<Oda> Odas
		{
			get
			{
				return this._Odas;
			}
			set
			{
				this._Odas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Odas(Oda entity)
		{
			this.SendPropertyChanging();
			entity.Paket = this;
		}
		
		private void detach_Odas(Oda entity)
		{
			this.SendPropertyChanging();
			entity.Paket = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OtelTanitims")]
	public partial class OtelTanitim : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _oteltanitimId;
		
		private string _Icerik;
		
		private string _ResimYolu;
		
		private string _otelTel;
		
		private string _otelFax;
		
		private string _otelEmail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnoteltanitimIdChanging(int value);
    partial void OnoteltanitimIdChanged();
    partial void OnIcerikChanging(string value);
    partial void OnIcerikChanged();
    partial void OnResimYoluChanging(string value);
    partial void OnResimYoluChanged();
    partial void OnotelTelChanging(string value);
    partial void OnotelTelChanged();
    partial void OnotelFaxChanging(string value);
    partial void OnotelFaxChanged();
    partial void OnotelEmailChanging(string value);
    partial void OnotelEmailChanged();
    #endregion
		
		public OtelTanitim()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oteltanitimId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int oteltanitimId
		{
			get
			{
				return this._oteltanitimId;
			}
			set
			{
				if ((this._oteltanitimId != value))
				{
					this.OnoteltanitimIdChanging(value);
					this.SendPropertyChanging();
					this._oteltanitimId = value;
					this.SendPropertyChanged("oteltanitimId");
					this.OnoteltanitimIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icerik", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Icerik
		{
			get
			{
				return this._Icerik;
			}
			set
			{
				if ((this._Icerik != value))
				{
					this.OnIcerikChanging(value);
					this.SendPropertyChanging();
					this._Icerik = value;
					this.SendPropertyChanged("Icerik");
					this.OnIcerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResimYolu", DbType="NVarChar(MAX)")]
		public string ResimYolu
		{
			get
			{
				return this._ResimYolu;
			}
			set
			{
				if ((this._ResimYolu != value))
				{
					this.OnResimYoluChanging(value);
					this.SendPropertyChanging();
					this._ResimYolu = value;
					this.SendPropertyChanged("ResimYolu");
					this.OnResimYoluChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otelTel", DbType="NVarChar(MAX)")]
		public string otelTel
		{
			get
			{
				return this._otelTel;
			}
			set
			{
				if ((this._otelTel != value))
				{
					this.OnotelTelChanging(value);
					this.SendPropertyChanging();
					this._otelTel = value;
					this.SendPropertyChanged("otelTel");
					this.OnotelTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otelFax", DbType="NVarChar(MAX)")]
		public string otelFax
		{
			get
			{
				return this._otelFax;
			}
			set
			{
				if ((this._otelFax != value))
				{
					this.OnotelFaxChanging(value);
					this.SendPropertyChanging();
					this._otelFax = value;
					this.SendPropertyChanged("otelFax");
					this.OnotelFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otelEmail", DbType="NVarChar(MAX)")]
		public string otelEmail
		{
			get
			{
				return this._otelEmail;
			}
			set
			{
				if ((this._otelEmail != value))
				{
					this.OnotelEmailChanging(value);
					this.SendPropertyChanging();
					this._otelEmail = value;
					this.SendPropertyChanged("otelEmail");
					this.OnotelEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Odas")]
	public partial class Oda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _odaId;
		
		private int _katNo;
		
		private string _odaTip;
		
		private string _durum;
		
		private double _fiyat;
		
		private System.Nullable<int> _Paket_paketId;
		
		private EntitySet<Rezervasyon> _Rezervasyons;
		
		private EntitySet<Musteri> _Musteris;
		
		private EntityRef<Paket> _Paket;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnodaIdChanging(int value);
    partial void OnodaIdChanged();
    partial void OnkatNoChanging(int value);
    partial void OnkatNoChanged();
    partial void OnodaTipChanging(string value);
    partial void OnodaTipChanged();
    partial void OndurumChanging(string value);
    partial void OndurumChanged();
    partial void OnfiyatChanging(double value);
    partial void OnfiyatChanged();
    partial void OnPaket_paketIdChanging(System.Nullable<int> value);
    partial void OnPaket_paketIdChanged();
    #endregion
		
		public Oda()
		{
			this._Rezervasyons = new EntitySet<Rezervasyon>(new Action<Rezervasyon>(this.attach_Rezervasyons), new Action<Rezervasyon>(this.detach_Rezervasyons));
			this._Musteris = new EntitySet<Musteri>(new Action<Musteri>(this.attach_Musteris), new Action<Musteri>(this.detach_Musteris));
			this._Paket = default(EntityRef<Paket>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int odaId
		{
			get
			{
				return this._odaId;
			}
			set
			{
				if ((this._odaId != value))
				{
					this.OnodaIdChanging(value);
					this.SendPropertyChanging();
					this._odaId = value;
					this.SendPropertyChanged("odaId");
					this.OnodaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_katNo", DbType="Int NOT NULL")]
		public int katNo
		{
			get
			{
				return this._katNo;
			}
			set
			{
				if ((this._katNo != value))
				{
					this.OnkatNoChanging(value);
					this.SendPropertyChanging();
					this._katNo = value;
					this.SendPropertyChanged("katNo");
					this.OnkatNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odaTip", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string odaTip
		{
			get
			{
				return this._odaTip;
			}
			set
			{
				if ((this._odaTip != value))
				{
					this.OnodaTipChanging(value);
					this.SendPropertyChanging();
					this._odaTip = value;
					this.SendPropertyChanged("odaTip");
					this.OnodaTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string durum
		{
			get
			{
				return this._durum;
			}
			set
			{
				if ((this._durum != value))
				{
					this.OndurumChanging(value);
					this.SendPropertyChanging();
					this._durum = value;
					this.SendPropertyChanged("durum");
					this.OndurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="Float NOT NULL")]
		public double fiyat
		{
			get
			{
				return this._fiyat;
			}
			set
			{
				if ((this._fiyat != value))
				{
					this.OnfiyatChanging(value);
					this.SendPropertyChanging();
					this._fiyat = value;
					this.SendPropertyChanged("fiyat");
					this.OnfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paket_paketId", DbType="Int")]
		public System.Nullable<int> Paket_paketId
		{
			get
			{
				return this._Paket_paketId;
			}
			set
			{
				if ((this._Paket_paketId != value))
				{
					if (this._Paket.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPaket_paketIdChanging(value);
					this.SendPropertyChanging();
					this._Paket_paketId = value;
					this.SendPropertyChanged("Paket_paketId");
					this.OnPaket_paketIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Oda_Rezervasyon", Storage="_Rezervasyons", ThisKey="odaId", OtherKey="Oda_odaId")]
		public EntitySet<Rezervasyon> Rezervasyons
		{
			get
			{
				return this._Rezervasyons;
			}
			set
			{
				this._Rezervasyons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Oda_Musteri", Storage="_Musteris", ThisKey="odaId", OtherKey="Oda_odaId")]
		public EntitySet<Musteri> Musteris
		{
			get
			{
				return this._Musteris;
			}
			set
			{
				this._Musteris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Paket_Oda", Storage="_Paket", ThisKey="Paket_paketId", OtherKey="paketId", IsForeignKey=true)]
		public Paket Paket
		{
			get
			{
				return this._Paket.Entity;
			}
			set
			{
				Paket previousValue = this._Paket.Entity;
				if (((previousValue != value) 
							|| (this._Paket.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Paket.Entity = null;
						previousValue.Odas.Remove(this);
					}
					this._Paket.Entity = value;
					if ((value != null))
					{
						value.Odas.Add(this);
						this._Paket_paketId = value.paketId;
					}
					else
					{
						this._Paket_paketId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Paket");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rezervasyons(Rezervasyon entity)
		{
			this.SendPropertyChanging();
			entity.Oda = this;
		}
		
		private void detach_Rezervasyons(Rezervasyon entity)
		{
			this.SendPropertyChanging();
			entity.Oda = null;
		}
		
		private void attach_Musteris(Musteri entity)
		{
			this.SendPropertyChanging();
			entity.Oda = this;
		}
		
		private void detach_Musteris(Musteri entity)
		{
			this.SendPropertyChanging();
			entity.Oda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Musteris")]
	public partial class Musteri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MusteriId;
		
		private string _Ad;
		
		private string _Soyad;
		
		private int _kimlikNo;
		
		private int _telefon;
		
		private System.Nullable<int> _Oda_odaId;
		
		private EntitySet<Rezervasyon> _Rezervasyons;
		
		private EntityRef<Oda> _Oda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMusteriIdChanging(int value);
    partial void OnMusteriIdChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnkimlikNoChanging(int value);
    partial void OnkimlikNoChanged();
    partial void OntelefonChanging(int value);
    partial void OntelefonChanged();
    partial void OnOda_odaIdChanging(System.Nullable<int> value);
    partial void OnOda_odaIdChanged();
    #endregion
		
		public Musteri()
		{
			this._Rezervasyons = new EntitySet<Rezervasyon>(new Action<Rezervasyon>(this.attach_Rezervasyons), new Action<Rezervasyon>(this.detach_Rezervasyons));
			this._Oda = default(EntityRef<Oda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MusteriId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MusteriId
		{
			get
			{
				return this._MusteriId;
			}
			set
			{
				if ((this._MusteriId != value))
				{
					this.OnMusteriIdChanging(value);
					this.SendPropertyChanging();
					this._MusteriId = value;
					this.SendPropertyChanged("MusteriId");
					this.OnMusteriIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kimlikNo", DbType="Int NOT NULL")]
		public int kimlikNo
		{
			get
			{
				return this._kimlikNo;
			}
			set
			{
				if ((this._kimlikNo != value))
				{
					this.OnkimlikNoChanging(value);
					this.SendPropertyChanging();
					this._kimlikNo = value;
					this.SendPropertyChanged("kimlikNo");
					this.OnkimlikNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="Int NOT NULL")]
		public int telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Oda_odaId", DbType="Int")]
		public System.Nullable<int> Oda_odaId
		{
			get
			{
				return this._Oda_odaId;
			}
			set
			{
				if ((this._Oda_odaId != value))
				{
					if (this._Oda.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOda_odaIdChanging(value);
					this.SendPropertyChanging();
					this._Oda_odaId = value;
					this.SendPropertyChanged("Oda_odaId");
					this.OnOda_odaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Musteri_Rezervasyon", Storage="_Rezervasyons", ThisKey="MusteriId", OtherKey="Musteri_MusteriId")]
		public EntitySet<Rezervasyon> Rezervasyons
		{
			get
			{
				return this._Rezervasyons;
			}
			set
			{
				this._Rezervasyons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Oda_Musteri", Storage="_Oda", ThisKey="Oda_odaId", OtherKey="odaId", IsForeignKey=true)]
		public Oda Oda
		{
			get
			{
				return this._Oda.Entity;
			}
			set
			{
				Oda previousValue = this._Oda.Entity;
				if (((previousValue != value) 
							|| (this._Oda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Oda.Entity = null;
						previousValue.Musteris.Remove(this);
					}
					this._Oda.Entity = value;
					if ((value != null))
					{
						value.Musteris.Add(this);
						this._Oda_odaId = value.odaId;
					}
					else
					{
						this._Oda_odaId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Oda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Rezervasyons(Rezervasyon entity)
		{
			this.SendPropertyChanging();
			entity.Musteri = this;
		}
		
		private void detach_Rezervasyons(Rezervasyon entity)
		{
			this.SendPropertyChanging();
			entity.Musteri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[__MigrationHistory]")]
	public partial class @__MigrationHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MigrationId;
		
		private string _ContextKey;
		
		private System.Data.Linq.Binary _Model;
		
		private string _ProductVersion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMigrationIdChanging(string value);
    partial void OnMigrationIdChanged();
    partial void OnContextKeyChanging(string value);
    partial void OnContextKeyChanged();
    partial void OnModelChanging(System.Data.Linq.Binary value);
    partial void OnModelChanged();
    partial void OnProductVersionChanging(string value);
    partial void OnProductVersionChanged();
    #endregion
		
		public @__MigrationHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MigrationId", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MigrationId
		{
			get
			{
				return this._MigrationId;
			}
			set
			{
				if ((this._MigrationId != value))
				{
					this.OnMigrationIdChanging(value);
					this.SendPropertyChanging();
					this._MigrationId = value;
					this.SendPropertyChanged("MigrationId");
					this.OnMigrationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContextKey", DbType="NVarChar(300) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ContextKey
		{
			get
			{
				return this._ContextKey;
			}
			set
			{
				if ((this._ContextKey != value))
				{
					this.OnContextKeyChanging(value);
					this.SendPropertyChanging();
					this._ContextKey = value;
					this.SendPropertyChanged("ContextKey");
					this.OnContextKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductVersion", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string ProductVersion
		{
			get
			{
				return this._ProductVersion;
			}
			set
			{
				if ((this._ProductVersion != value))
				{
					this.OnProductVersionChanging(value);
					this.SendPropertyChanging();
					this._ProductVersion = value;
					this.SendPropertyChanged("ProductVersion");
					this.OnProductVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
